# Generated by Django 4.0.1 on 2022-01-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('complain', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='citizens',
            name='email',
            field=models.EmailField(max_length=70),
        ),
    ]
