# Generated by Django 4.0.1 on 2022-01-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0002_feedback_alter_citizens_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
                ('citizenaddress', models.CharField(max_length=200)),
                ('typeofwaste', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='citizens',
            name='citizenaddress',
        ),
        migrations.AlterField(
            model_name='citizens',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='citizens',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='citizens',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
