# Generated by Django 4.0.1 on 2022-01-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0003_request_remove_citizens_citizenaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='username',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
